server:
  forward-headers-strategy: framework

spring:
  profiles:
    active: default,local

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  rabbitmq:
    addresses: rabbitmq
    port: 5672

  cloud:
    stream:
      bindings:
        publishCaseImport-out-0:
          destination: case.import
      source: publishCaseImport

  data:
    elasticsearch:
      enabled : false
      host: elasticsearch
      port: 9200
      client:
        timeout : 60  # Seconds
